services:
  postgres:
    extends:
      file: docker-compose.dev.yml
      service: postgres
  minio:
    extends:
      file: docker-compose.dev.yml
      service: minio
  createbuckets:
    extends:
      file: docker-compose.dev.yml
      service: createbuckets
  postgres_test_db:
    extends:
      file: docker-compose.dev.yml
      service: postgres_test_db
    volumes:
      - ./turntable-test-db/turntable-test-db/postgres_test_db_data:/var/lib/postgresql/data
  metabase:
    extends:
      file: docker-compose.dev.yml
      service: metabase


volumes:
  postgres_data:
  minio_data:


networks:
  default:
    name: app_network
    driver: bridge