
databases:
- name: postgres
  databaseName: db
  user: db_user
  plan: free
  region: ohio
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
services:
- type: web
  name: api
  runtime: docker
  repo: https://github.com/turntable-so/turntable
  branch: justin/eng-1074-harden-app-encryption
  plan: free
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: postgres
      property: connectionString
  - key: BACKEND_HOST
    fromService:
      type: web
      name: api
      envVarKey: RENDER_EXTERNAL_URL
  # env variables from other services
  - key: AWS_S3_ACCESS_KEY_ID
    fromService:
      name: minio-server
      type: web
      envVarKey: MINIO_ROOT_USER
  - key: AWS_S3_SECRET_ACCESS_KEY
    fromService:
      name: minio-server
      type: web
      envVarKey: MINIO_ROOT_PASSWORD
  - fromGroup: settings
  - fromGroup: storage
  - fromGroup: mandatory_inputs
  - fromGroup: optional_inputs

  region: ohio
  dockerCommand: python -m gunicorn api.asgi:application -k uvicorn.workers.UvicornWorker
  dockerContext: .
  dockerfilePath: Dockerfile
  rootDir: backend
- type: worker
  name: worker
  runtime: docker
  repo: https://github.com/turntable-so/turntable
  branch: justin/eng-1074-harden-app-encryption
  plan: free
  region: ohio
  dockerCommand: python workflows/main.py
  dockerContext: .
  dockerfilePath: Dockerfile
  rootDir: backend
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: postgres
      property: connectionString
  - key: BACKEND_HOST
    fromService:
      type: web
      name: api
      envVarKey: RENDER_EXTERNAL_URL
  - key: AWS_S3_ACCESS_KEY_ID
    fromService:
      name: minio-server
      type: web
      envVarKey: MINIO_ROOT_USER
  - key: AWS_S3_SECRET_ACCESS_KEY
    fromService:
      name: minio-server
      type: web
      envVarKey: MINIO_ROOT_PASSWORD
  - fromGroup: settings
  - fromGroup: storage
  - fromGroup: mandatory_inputs
  - fromGroup: optional_inputs

# support services
- type: web
  name: minio-server
  healthCheckPath: /minio/health/live
  runtime: image
  image:
    url: docker.io/minio/minio:latest
  plan: starter
  region: ohio
  dockerCommand: minio server /data --address $MINIO_HOST:$MINIO_PORT --console-address $MINIO_HOST:$MINIO_CONSOLE_PORT
  autoDeploy: false
  disk:
    name: data
    mountPath: /data
  envVars:
  - key: MINIO_ROOT_USER
    generateValue: true
  - key: MINIO_ROOT_PASSWORD
    generateValue: true
  - key: MINIO_HOST
    value: "0.0.0.0"
  - key: MINIO_PORT
    value: 9000
  - key: MINIO_CONSOLE_PORT
    value: 9090

- type: web
  name: minio-console
  runtime: docker
  plan: free
  region: ohio
  dockerContext: /
  dockerfilePath: ./Dockerfile
  autoDeploy: false
  envVars:
  - key: PORT
    value: 10000
  - key: MINIO_HOST
    fromService:
      name: minio-server
      type: web
      property: host
  - key: MINIO_CONSOLE_PORT
    fromService:
      name: minio-server
      type: web
      envVarKey: CONSOLE_PORT

envVarGroups:
  - name: settings
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: api.settings
      - key: ENCRYPTION_KEY
        generateValue: true

  - name: storage
    envVars:
      - key: AWS_STORAGE_BUCKET_NAME
        value: artifacts
      - key: AWS_S3_ENDPOINT_URL
        value: http://0.0.0.0:9000

  - name: mandatory_inputs
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: HATCHET_CLIENT_TOKEN
        sync: false


  - name: optional_inputs
    envVars:
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GITHUB_APP_ID
        sync: false
      - key: GITHUB_PRIVATE_KEY_BASE64
        sync: false
      - key: GITHUB_WEBHOOK_SECRET
        sync: false


    
version: "1"
