# # type: ignore
# from vinyl import Field, source # noqa F401
# from vinyl import types as t # noqa F401

# from dev.resources import european_football_2 # noqa F401 


# @source(resource=european_football_2)
# class Match:
#     _table = "Match"
#     _unique_name = "european_football_2.european_football_2.main.Match"
#     _schema = "main"
#     _database = "european_football_2"
#     _twin_path = "data/european_football_2/main/european_football_2.duckdb"
#     _path = "data/dev_databases/european_football_2/european_football_2.sqlite"
#     _row_count = 25979
#     _col_replace = {}

#     id: t.Int64(nullable=True) = Field(description='''the unique id for matches''', primary_key=True)
#     country_id: t.Int64(nullable=True) = Field(description='''country id''')
#     league_id: t.Int64(nullable=True) = Field(description='''league id''')
#     season: t.String(nullable=True) = Field(description='''the season of the match''')
#     stage: t.Int64(nullable=True) = Field(description='''the stage of the match''')
#     date: t.String(nullable=True) = Field(description='''the date of the match. Additional context: e.g. 2008-08-17 00:00:00''')
#     match_api_id: t.Int64(nullable=True) = Field(description='''the id of the match api''')
#     home_team_api_id: t.Int64(nullable=True) = Field(description='''the id of the home team api''', foreign_key=('Team', '_team_api_id'))
#     away_team_api_id: t.Int64(nullable=True) = Field(description='''the id of the away team api''', foreign_key=('Team', '_team_api_id'))
#     home_team_goal: t.Int64(nullable=True) = Field(description='''the goal of the home team''')
#     away_team_goal: t.Int64(nullable=True) = Field(description='''the goal of the away team''')
#     home_player_X1: t.Int64(nullable=True)
#     home_player_X2: t.Int64(nullable=True)
#     home_player_X3: t.Int64(nullable=True)
#     home_player_X4: t.Int64(nullable=True)
#     home_player_X5: t.Int64(nullable=True)
#     home_player_X6: t.Int64(nullable=True)
#     home_player_X7: t.Int64(nullable=True)
#     home_player_X8: t.Int64(nullable=True)
#     home_player_X9: t.Int64(nullable=True)
#     home_player_X10: t.Int64(nullable=True)
#     home_player_X11: t.Int64(nullable=True)
#     away_player_X1: t.Int64(nullable=True)
#     away_player_X2: t.Int64(nullable=True)
#     away_player_X3: t.Int64(nullable=True)
#     away_player_X4: t.Int64(nullable=True)
#     away_player_X5: t.Int64(nullable=True)
#     away_player_X6: t.Int64(nullable=True)
#     away_player_X7: t.Int64(nullable=True)
#     away_player_X8: t.Int64(nullable=True)
#     away_player_X9: t.Int64(nullable=True)
#     away_player_X10: t.Int64(nullable=True)
#     away_player_X11: t.Int64(nullable=True)
#     home_player_Y1: t.Int64(nullable=True)
#     home_player_Y2: t.Int64(nullable=True)
#     home_player_Y3: t.Int64(nullable=True)
#     home_player_Y4: t.Int64(nullable=True)
#     home_player_Y5: t.Int64(nullable=True)
#     home_player_Y6: t.Int64(nullable=True)
#     home_player_Y7: t.Int64(nullable=True)
#     home_player_Y8: t.Int64(nullable=True)
#     home_player_Y9: t.Int64(nullable=True)
#     home_player_Y10: t.Int64(nullable=True)
#     home_player_Y11: t.Int64(nullable=True)
#     away_player_Y1: t.Int64(nullable=True)
#     away_player_Y2: t.Int64(nullable=True)
#     away_player_Y3: t.Int64(nullable=True)
#     away_player_Y4: t.Int64(nullable=True)
#     away_player_Y5: t.Int64(nullable=True)
#     away_player_Y6: t.Int64(nullable=True)
#     away_player_Y7: t.Int64(nullable=True)
#     away_player_Y8: t.Int64(nullable=True)
#     away_player_Y9: t.Int64(nullable=True)
#     away_player_Y10: t.Int64(nullable=True)
#     away_player_Y11: t.Int64(nullable=True)
#     home_player_1: t.Int64(nullable=True) = Field(foreign_key=('Player', 'player_api_id'))
#     home_player_2: t.Int64(nullable=True) = Field(foreign_key=('Player', 'player_api_id'))
#     home_player_3: t.Int64(nullable=True) = Field(foreign_key=('Player', 'player_api_id'))
#     home_player_4: t.Int64(nullable=True) = Field(foreign_key=('Player', 'player_api_id'))
#     home_player_5: t.Int64(nullable=True) = Field(foreign_key=('Player', 'player_api_id'))
#     home_player_6: t.Int64(nullable=True) = Field(foreign_key=('Player', 'player_api_id'))
#     home_player_7: t.Int64(nullable=True) = Field(foreign_key=('Player', 'player_api_id'))
#     home_player_8: t.Int64(nullable=True) = Field(foreign_key=('Player', 'player_api_id'))
#     home_player_9: t.Int64(nullable=True) = Field(foreign_key=('Player', 'player_api_id'))
#     home_player_10: t.Int64(nullable=True) = Field(foreign_key=('Player', 'player_api_id'))
#     home_player_11: t.Int64(nullable=True) = Field(foreign_key=('Player', 'player_api_id'))
#     away_player_1: t.Int64(nullable=True) = Field(foreign_key=('Player', 'player_api_id'))
#     away_player_2: t.Int64(nullable=True) = Field(foreign_key=('Player', 'player_api_id'))
#     away_player_3: t.Int64(nullable=True) = Field(foreign_key=('Player', 'player_api_id'))
#     away_player_4: t.Int64(nullable=True) = Field(foreign_key=('Player', 'player_api_id'))
#     away_player_5: t.Int64(nullable=True) = Field(foreign_key=('Player', 'player_api_id'))
#     away_player_6: t.Int64(nullable=True) = Field(foreign_key=('Player', 'player_api_id'))
#     away_player_7: t.Int64(nullable=True) = Field(foreign_key=('Player', 'player_api_id'))
#     away_player_8: t.Int64(nullable=True) = Field(foreign_key=('Player', 'player_api_id'))
#     away_player_9: t.Int64(nullable=True) = Field(foreign_key=('Player', 'player_api_id'))
#     away_player_10: t.Int64(nullable=True) = Field(foreign_key=('Player', 'player_api_id'))
#     away_player_11: t.Int64(nullable=True) = Field(foreign_key=('Player', 'player_api_id'))
#     goal: t.String(nullable=True) = Field(description='''the goal of the match''')
#     shoton: t.String(nullable=True) = Field(description='''the shot on goal of the match. Additional context: commonsense reasoning: 
# A shot on goal is a shot that enters the goal or would have entered the goal if it had not been blocked by the goalkeeper or another defensive player.
# ''')
#     shotoff: t.String(nullable=True) = Field(description='''the shot off goal of the match, which is the opposite of shot on''')
#     foulcommit: t.String(nullable=True) = Field(description='''the fouls occurred in the match''')
#     card: t.String(nullable=True) = Field(description='''the cards given in the match''')
#     cross: t.String(nullable=True) = Field(description='''Balls sent into the opposition team's area from a wide position in the match''')
#     corner: t.String(nullable=True) = Field(description='''Ball goes out of play for a corner kick in the match''')
#     possession: t.String(nullable=True) = Field(description='''The duration from a player taking over the ball in the match''')
#     B365H: t.Float64(nullable=True)
#     B365D: t.Float64(nullable=True)
#     B365A: t.Float64(nullable=True)
#     BWH: t.Float64(nullable=True)
#     BWD: t.Float64(nullable=True)
#     BWA: t.Float64(nullable=True)
#     IWH: t.Float64(nullable=True)
#     IWD: t.Float64(nullable=True)
#     IWA: t.Float64(nullable=True)
#     LBH: t.Float64(nullable=True)
#     LBD: t.Float64(nullable=True)
#     LBA: t.Float64(nullable=True)
#     PSH: t.Float64(nullable=True)
#     PSD: t.Float64(nullable=True)
#     PSA: t.Float64(nullable=True)
#     WHH: t.Float64(nullable=True)
#     WHD: t.Float64(nullable=True)
#     WHA: t.Float64(nullable=True)
#     SJH: t.Float64(nullable=True)
#     SJD: t.Float64(nullable=True)
#     SJA: t.Float64(nullable=True)
#     VCH: t.Float64(nullable=True)
#     VCD: t.Float64(nullable=True)
#     VCA: t.Float64(nullable=True)
#     GBH: t.Float64(nullable=True)
#     GBD: t.Float64(nullable=True)
#     GBA: t.Float64(nullable=True)
#     BSH: t.Float64(nullable=True)
#     BSD: t.Float64(nullable=True)
#     BSA: t.Float64(nullable=True)

