# Generated by Django 5.0.6 on 2024-11-04 22:36

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension

import app.models.workspace
import app.services.storage_backends
import app.utils.fields
import vinyl.lib.dbt_methods


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("django_celery_results", "0011_taskresult_periodic_task_name"),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.TextField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("model", "Model"),
                            ("source", "Source"),
                            ("seed", "Seed"),
                            ("analysis", "Analysis"),
                            ("metric", "Metric"),
                            ("snapshot", "Snapshot"),
                            ("view", "View"),
                            ("chart", "Chart"),
                            ("dashboard", "Dashboard"),
                            ("dataset", "Dataset"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(null=True)),
                ("ai_description", models.TextField(null=True)),
                ("sql", models.TextField(null=True)),
                ("config", models.JSONField(null=True)),
                ("unique_name", models.TextField(null=True)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "tests",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "materialization",
                    models.TextField(
                        choices=[
                            ("view", "View"),
                            ("table", "Table"),
                            ("materialized_view", "Materialized View"),
                            ("ephemeral", "Ephemeral"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "db_location",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("is_indirect", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="AssetContainer",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("workbook", "Workbook"),
                            ("project", "Project"),
                            ("database", "Database"),
                            ("schema", "Schema"),
                            ("workspace", "Workspace"),
                        ],
                        max_length=255,
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ResourceDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DBTResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("manifest_json", models.JSONField(null=True)),
                ("catalog_json", models.JSONField(null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("main_branch_name", models.CharField(default="main", max_length=255)),
                ("git_repo_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(null=True)),
                (
                    "type",
                    models.TextField(
                        choices=[("db", "Database"), ("bi", "BI Tool")], null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("datahub_db", models.FileField(null=True, upload_to="datahub_dbs/")),
            ],
        ),
        migrations.CreateModel(
            name="SSHKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("public_key", models.TextField()),
                ("private_key", app.utils.fields.encrypt(models.TextField())),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("profile_image_url", models.URLField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.TextField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.TextField()),
                ("type", models.TextField(null=True)),
                ("nullable", models.BooleanField(null=True)),
                ("description", models.TextField(null=True)),
                ("ai_description", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tests",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
                ("is_indirect", models.BooleanField(default=False)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="app.asset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataFileDetails",
            fields=[
                (
                    "resourcedetails_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.resourcedetails",
                    ),
                ),
                ("subtype", models.CharField(default="file", max_length=255)),
                ("path", models.TextField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("app.resourcedetails",),
        ),
        migrations.CreateModel(
            name="DBDetails",
            fields=[
                (
                    "resourcedetails_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.resourcedetails",
                    ),
                ),
                ("lookback_days", models.IntegerField(default=1)),
                (
                    "database_include",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "database_exclude",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "schema_include",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "schema_exclude",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "table_include",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "table_exclude",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        null=True,
                        size=None,
                    ),
                ),
                ("use_only_dbt_schemas", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("app.resourcedetails",),
        ),
        migrations.CreateModel(
            name="MetabaseDetails",
            fields=[
                (
                    "resourcedetails_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.resourcedetails",
                    ),
                ),
                ("subtype", models.CharField(default="metabase", max_length=255)),
                (
                    "username",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
                (
                    "password",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
                (
                    "connect_uri",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
                (
                    "api_key",
                    app.utils.fields.encrypt(
                        models.CharField(blank=True, max_length=255, null=True)
                    ),
                ),
                (
                    "jwt_shared_secret",
                    app.utils.fields.encrypt(
                        models.CharField(blank=True, max_length=255, null=True)
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("app.resourcedetails",),
        ),
        migrations.CreateModel(
            name="PowerBIDetails",
            fields=[
                (
                    "resourcedetails_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.resourcedetails",
                    ),
                ),
                ("subtype", models.CharField(default="powerbi", max_length=255)),
                (
                    "client_id",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
                (
                    "client_secret",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
                (
                    "powerbi_workspace_id",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
                (
                    "powerbi_tenant_id",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("app.resourcedetails",),
        ),
        migrations.CreateModel(
            name="TableauDetails",
            fields=[
                (
                    "resourcedetails_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.resourcedetails",
                    ),
                ),
                ("subtype", models.CharField(default="tableau", max_length=255)),
                (
                    "connect_uri",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
                (
                    "site",
                    app.utils.fields.encrypt(
                        models.CharField(blank=True, default="", max_length=255)
                    ),
                ),
                (
                    "username",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
                (
                    "password",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("app.resourcedetails",),
        ),
        migrations.CreateModel(
            name="DBTCloudDetails",
            fields=[
                (
                    "dbtresource_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.dbtresource",
                    ),
                ),
                ("subtype", models.CharField(default="dbt_cloud", max_length=255)),
                (
                    "api_token",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
                (
                    "account_id",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
                (
                    "project_id",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("app.dbtresource",),
        ),
        migrations.AddField(
            model_name="dbtresource",
            name="creator",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dbtresource",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.CreateModel(
            name="Notebook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(null=True)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("tenant_id", models.TextField(null=True)),
                ("contents", models.JSONField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notebooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("branch_name", models.CharField(max_length=255)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="app.repository",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="resourcedetails",
            name="resource",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="app.resource",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="creator",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dbtresource",
            name="resource",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.resource",
            ),
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("config", models.JSONField(null=True)),
                (
                    "results",
                    models.FileField(
                        null=True,
                        storage=app.services.storage_backends.CustomS3Boto3Storage(),
                        upload_to="results/",
                    ),
                ),
                (
                    "notebook",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="app.notebook",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blocks",
                        to="app.resource",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="asset",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.resource"
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="ssh_key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.sshkey"
            ),
        ),
        migrations.CreateModel(
            name="WorkflowRun",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("FAILED", "Failed"),
                            ("SUCCESS", "Success"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "resource",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_runs",
                        to="app.resource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IngestError",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("command", models.TextField(null=True)),
                ("error", models.JSONField(null=True)),
                (
                    "workflow_run",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingest_errors",
                        to="app.workflowrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=app.models.workspace.generate_short_uuid,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("icon_url", models.URLField(blank=True, null=True)),
                (
                    "icon_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=app.services.storage_backends.PublicMediaStorage(),
                        upload_to="assets/icons/",
                    ),
                ),
                (
                    "assets_exclude_name_contains",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="workspaces", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "permissions": [("manage_workspace", "Can manage workspace")],
            },
        ),
        migrations.AddField(
            model_name="sshkey",
            name="workspace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.workspace",
            ),
        ),
        migrations.CreateModel(
            name="ScheduledWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "workflow_type",
                    models.CharField(
                        choices=[("cron", "Cron"), ("one_time", "One Time")],
                        editable=False,
                        max_length=255,
                    ),
                ),
                ("one_off", models.BooleanField(null=True)),
                (
                    "replacement_identifier",
                    models.CharField(
                        db_comment="The identifier of the periodic task that determines whether a new workflow should be created or an existing workflow should be updated",
                        editable=False,
                        max_length=64,
                    ),
                ),
                (
                    "aggregation_identifier",
                    models.CharField(
                        db_comment="The identifier of the periodic task that determines which other workflows this should be aggregated with in the frontend",
                        editable=False,
                        max_length=64,
                    ),
                ),
                (
                    "clocked",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_celery_beat.clockedschedule",
                    ),
                ),
                (
                    "crontab",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_celery_beat.crontabschedule",
                    ),
                ),
                (
                    "periodic_task",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_celery_beat.periodictask",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.workspace"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.AddField(
            model_name="resourcedetails",
            name="workspace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.workspace",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="workspace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to="app.workspace",
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.workspace"
            ),
        ),
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("sql", models.TextField(null=True)),
                (
                    "results",
                    models.FileField(
                        null=True,
                        storage=app.services.storage_backends.CustomS3Boto3Storage(),
                        upload_to="query_results/",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.branch",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.resource"
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.workspace"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="notebook",
            name="workspace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notebooks",
                to="app.workspace",
            ),
        ),
        migrations.AddField(
            model_name="dbtresource",
            name="workspace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.workspace",
            ),
        ),
        migrations.CreateModel(
            name="DBTQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("dbt_sql", models.TextField(null=True)),
                (
                    "results",
                    models.FileField(
                        null=True,
                        storage=app.services.storage_backends.CustomS3Boto3Storage(),
                        upload_to="dbt_query_results/",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.branch",
                    ),
                ),
                (
                    "dbtresource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.dbtresource",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.workspace"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContainerMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.asset"
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.assetcontainer",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.workspace"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ColumnLink",
            fields=[
                (
                    "id",
                    models.TextField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "lineage_type",
                    models.CharField(
                        choices=[("all", "All"), ("direct_only", "Direct Only")],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "connection_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("confidence", models.FloatField(null=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="app.column",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_links",
                        to="app.column",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.workspace"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="column",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.workspace"
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.workspace"
            ),
        ),
        migrations.CreateModel(
            name="AssetLink",
            fields=[
                (
                    "id",
                    models.TextField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="app.asset",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_links",
                        to="app.asset",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.workspace"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetError",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("error", models.JSONField(null=True)),
                ("lineage_type", models.TextField(null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.asset"
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "autocomplete_vector",
                    pgvector.django.vector.VectorField(dimensions=1536, null=True),
                ),
                (
                    "search_vector",
                    pgvector.django.vector.VectorField(dimensions=1536, null=True),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.asset"
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.workspace"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assetcontainer",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.workspace"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.workspace"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="active_workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.workspace",
            ),
        ),
        migrations.CreateModel(
            name="WorkspaceGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "permissions",
                    models.ManyToManyField(blank=True, to="auth.permission"),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="workspace_groups", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="app.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BigqueryDetails",
            fields=[
                (
                    "dbdetails_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.dbdetails",
                    ),
                ),
                ("subtype", models.CharField(default="bigquery", max_length=255)),
                ("service_account", app.utils.fields.encrypt(models.JSONField())),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("app.dbdetails",),
        ),
        migrations.CreateModel(
            name="DatabricksDetails",
            fields=[
                (
                    "dbdetails_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.dbdetails",
                    ),
                ),
                ("subtype", models.CharField(default="databricks", max_length=255)),
                ("host", app.utils.fields.encrypt(models.CharField(max_length=255))),
                ("token", app.utils.fields.encrypt(models.CharField(max_length=255))),
                (
                    "http_path",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("app.dbdetails",),
        ),
        migrations.CreateModel(
            name="DuckDBDetails",
            fields=[
                (
                    "dbdetails_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.dbdetails",
                    ),
                ),
                ("subtype", models.CharField(default="duckdb", max_length=255)),
                ("path", app.utils.fields.encrypt(models.TextField())),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("app.dbdetails",),
        ),
        migrations.CreateModel(
            name="PostgresDetails",
            fields=[
                (
                    "dbdetails_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.dbdetails",
                    ),
                ),
                ("subtype", models.CharField(default="postgres", max_length=255)),
                ("host", app.utils.fields.encrypt(models.CharField(max_length=255))),
                ("port", models.IntegerField()),
                (
                    "database",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
                (
                    "username",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
                (
                    "password",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("app.dbdetails",),
        ),
        migrations.CreateModel(
            name="RedshiftDetails",
            fields=[
                (
                    "dbdetails_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.dbdetails",
                    ),
                ),
                ("subtype", models.CharField(default="redshift", max_length=255)),
                ("host", app.utils.fields.encrypt(models.CharField(max_length=255))),
                ("port", models.IntegerField()),
                (
                    "database",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
                (
                    "username",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
                (
                    "password",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
                ("serverless", models.BooleanField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("app.dbdetails",),
        ),
        migrations.CreateModel(
            name="SnowflakeDetails",
            fields=[
                (
                    "dbdetails_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.dbdetails",
                    ),
                ),
                ("subtype", models.CharField(default="snowflake", max_length=255)),
                ("account", app.utils.fields.encrypt(models.CharField(max_length=255))),
                (
                    "warehouse",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
                (
                    "username",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
                (
                    "password",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
                ("role", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("app.dbdetails",),
        ),
        migrations.CreateModel(
            name="LookerDetails",
            fields=[
                (
                    "resourcedetails_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.resourcedetails",
                    ),
                ),
                ("subtype", models.CharField(default="looker", max_length=255)),
                ("base_url", app.utils.fields.encrypt(models.URLField())),
                (
                    "client_id",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
                (
                    "client_secret",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
                (
                    "github_repo_id",
                    app.utils.fields.encrypt(
                        models.CharField(max_length=255, null=True)
                    ),
                ),
                ("project_path", models.CharField(max_length=255, null=True)),
                (
                    "repository",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.repository",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("app.resourcedetails",),
        ),
        migrations.CreateModel(
            name="DBTCoreDetails",
            fields=[
                (
                    "dbtresource_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.dbtresource",
                    ),
                ),
                ("subtype", models.CharField(default="dbt", max_length=255)),
                ("project_path", models.CharField(max_length=255)),
                (
                    "database",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
                ("schema", app.utils.fields.encrypt(models.CharField(max_length=255))),
                (
                    "other_schemas",
                    app.utils.fields.encrypt(models.JSONField(null=True)),
                ),
                ("threads", models.IntegerField(default=1, null=True)),
                (
                    "version",
                    models.CharField(
                        choices=[
                            (vinyl.lib.dbt_methods.DBTVersion["V1_3"], "1.3"),
                            (vinyl.lib.dbt_methods.DBTVersion["V1_4"], "1.4"),
                            (vinyl.lib.dbt_methods.DBTVersion["V1_5"], "1.5"),
                            (vinyl.lib.dbt_methods.DBTVersion["V1_6"], "1.6"),
                            (vinyl.lib.dbt_methods.DBTVersion["V1_7"], "1.7"),
                            (vinyl.lib.dbt_methods.DBTVersion["V1_8"], "1.8"),
                        ],
                        max_length=255,
                    ),
                ),
                ("env_vars", app.utils.fields.encrypt(models.JSONField(null=True))),
                (
                    "repository",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.repository",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("app.dbtresource",),
        ),
        migrations.CreateModel(
            name="DBTOrchestrator",
            fields=[
                (
                    "scheduledworkflow_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.scheduledworkflow",
                    ),
                ),
                (
                    "commands",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.branch",
                    ),
                ),
                (
                    "dbt_resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dbt_orchestrator",
                        to="app.dbtresource",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.resource"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("app.scheduledworkflow",),
        ),
        migrations.CreateModel(
            name="MetadataSyncWorkflow",
            fields=[
                (
                    "scheduledworkflow_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.scheduledworkflow",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.resource"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("app.scheduledworkflow",),
        ),
        migrations.AddIndex(
            model_name="sshkey",
            index=models.Index(
                fields=["workspace_id"], name="app_sshkey_workspa_cacad8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resourcedetails",
            index=models.Index(
                fields=["resource_id"], name="app_resourc_resourc_4c9b2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["workspace_id"], name="app_resourc_workspa_c9e70d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(
                fields=["workspace_id"], name="app_reposit_workspa_3bc0a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notebook",
            index=models.Index(
                fields=["tenant_id"], name="app_noteboo_tenant__62c3d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="columnlink",
            index=models.Index(
                fields=["workspace_id"], name="app_columnl_workspa_660691_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="columnlink",
            index=models.Index(
                fields=["source_id"], name="app_columnl_source__d14bd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="columnlink",
            index=models.Index(
                fields=["target_id"], name="app_columnl_target__fc5751_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="column",
            index=models.Index(
                fields=["workspace_id"], name="app_column_workspa_f8b31e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="column",
            index=models.Index(
                fields=["asset_id"], name="app_column_asset_i_963a8b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="branch",
            unique_together={("branch_name", "repository", "workspace")},
        ),
        migrations.AddIndex(
            model_name="assetlink",
            index=models.Index(
                fields=["source_id", "target_id"], name="app_assetli_source__d2fe60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetlink",
            index=models.Index(
                fields=["workspace_id"], name="app_assetli_workspa_e0ae34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asseterror",
            index=models.Index(
                fields=["workspace_id"], name="app_asseter_workspa_b49433_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetembedding",
            index=models.Index(
                fields=["workspace_id"], name="app_assetem_workspa_01aa20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["workspace_id"], name="app_asset_workspa_f5721a_idx"
            ),
        ),
    ]
