# Generated by Django 5.0.6 on 2024-07-09 02:52

import django.db.models.deletion
import pgvector.django.vector
from pgvector.django import VectorExtension
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="AssetEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.TextField(null=True)),
                (
                    "autocomplete_vector",
                    pgvector.django.vector.VectorField(dimensions=1536, null=True),
                ),
                (
                    "search_vector",
                    pgvector.django.vector.VectorField(dimensions=1536, null=True),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.asset"
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.repository",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant_id"], name="app_assetem_tenant__c8d070_idx"
                    )
                ],
            },
        ),
    ]
