# Generated by Django 5.0.6 on 2024-08-19 19:29

import app.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbtcoredetails",
            name="deploy_key",
            field=app.utils.fields.encrypt(models.TextField(null=True)),
        ),
        migrations.AddField(
            model_name="dbtcoredetails",
            name="git_repo_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="dbtcoredetails",
            name="main_git_branch",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="dbtclouddetails",
            name="subtype",
            field=models.CharField(default="dbt_cloud", max_length=255),
        ),
        migrations.AlterField(
            model_name="dbtcoredetails",
            name="subtype",
            field=models.CharField(default="dbt", max_length=255),
        ),
    ]
