# Generated by Django 5.0.6 on 2024-08-20 23:49

from django.db import migrations, models

import app.utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE app_dbtcoredetails
                ALTER COLUMN other_schemas
                TYPE bytea
                USING array_to_string(other_schemas, ',')::bytea;
            """,
            reverse_sql="""
                ALTER TABLE app_dbtcoredetails
                ALTER COLUMN other_schemas
                TYPE character varying[]
                USING string_to_array(other_schemas::text, ',');
            """,
        ),
        migrations.AlterField(
            model_name="dbtcoredetails",
            name="other_schemas",
            field=app.utils.fields.encrypt(models.JSONField(null=True)),
        ),
    ]
