# Generated by Django 5.0.6 on 2024-09-01 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestError",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("command", models.TextField(null=True)),
                ("error", models.JSONField(null=True)),
                (
                    "workflow_run",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingest_errors",
                        to="app.workflowrun",
                    ),
                ),
            ],
        ),
    ]
