# Generated by Django 5.0.6 on 2024-08-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_dbtcoredetails_deploy_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dbtcoredetails",
            name="git_repo_url",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
