# Generated by Django 5.0.6 on 2024-08-22 18:20

import app.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_dbtcoredetails_git_repo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metabasedetails",
            name="connect_uri",
            field=app.utils.fields.encrypt(models.CharField(max_length=255)),
        ),
    ]
