# Generated by Django 5.0.6 on 2024-09-06 15:04

import app.utils.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_asset_is_indirect_column_is_indirect"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "secret_value",
                    app.utils.fields.encrypt(
                        models.CharField(max_length=512, null=True)
                    ),
                ),
                ("plaintext_value", models.CharField(max_length=512, null=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="app.workspace",
                    ),
                ),
            ],
        ),
    ]
