# Generated by Django 5.0.6 on 2024-08-27 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_metabasedetails_connect_uri"),
    ]

    operations = [
        migrations.AlterField(
            model_name="column",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="app.asset",
            ),
        ),
    ]
