# Generated by Django 5.0.6 on 2024-08-23 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_dbtcoredetails_other_schemas"),
        ("app", "0004_alter_metabasedetails_connect_uri"),
    ]

    operations = []
