# Generated by Django 5.0.6 on 2024-09-07 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_databricksdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active_workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.workspace",
            ),
        ),
    ]
