# Generated by Django 5.0.6 on 2024-09-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_workspacesetting"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="workspacesetting",
            index=models.Index(
                fields=["name", "workspace"], name="app_workspa_name_91f1ad_idx"
            ),
        ),
    ]
