# Generated by Django 5.0.6 on 2024-09-07 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_user_active_workspace"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableauDetails",
            fields=[
                (
                    "resourcedetails_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.resourcedetails",
                    ),
                ),
                ("subtype", models.CharField(default="tableau", max_length=255)),
                (
                    "connect_uri",
                    app.utils.encrypt_fields.encrypt(models.CharField(max_length=255)),
                ),
                (
                    "site",
                    app.utils.encrypt_fields.encrypt(
                        models.CharField(blank=True, default="", max_length=255)
                    ),
                ),
                (
                    "username",
                    app.utils.encrypt_fields.encrypt(models.CharField(max_length=255)),
                ),
                (
                    "password",
                    app.utils.encrypt_fields.encrypt(models.CharField(max_length=255)),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("app.resourcedetails",),
        ),
    ]
