# Generated by Django 5.0.6 on 2024-07-10 15:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_column_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repository",
            name="resource",
        ),
        migrations.AddField(
            model_name="repository",
            name="resources",
            field=models.ManyToManyField(
                related_name="repositories", to="app.resource"
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=255,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
