# Generated by Django 5.0.6 on 2024-09-08 18:42

import app.models.workspace
import app.utils.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_user_active_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="config",
            field=models.JSONField(
                default=app.models.workspace.default_workspace_config
            ),
        ),
        migrations.CreateModel(
            name="WorkspaceSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "openai_api_key",
                    app.utils.fields.encrypt(models.TextField(null=True)),
                ),
                (
                    "anthropic_api_key",
                    app.utils.fields.encrypt(models.TextField(null=True)),
                ),
                (
                    "workspace",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="app.workspace",
                    ),
                ),
            ],
        ),
    ]
