# Generated by Django 5.0.6 on 2024-09-10 13:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_tableaudetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="AssetContainer",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("workbook", "Workbook"),
                            ("project", "Project"),
                            ("database", "Database"),
                            ("schema", "Schema"),
                        ],
                        max_length=255,
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField(null=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetContainerMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.asset"
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.assetcontainer",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.workspace",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="asset",
            name="containers",
            field=models.ManyToManyField(
                related_name="assets",
                through="app.AssetContainerMembership",
                to="app.assetcontainer",
            ),
        ),
    ]
