# Generated by Django 5.0.6 on 2024-07-10 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_repository_resource_repository_resources_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repository",
            name="resources",
        ),
        migrations.AddField(
            model_name="repository",
            name="resource",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.resource",
            ),
        ),
    ]
