# Generated by Django 5.0.6 on 2024-09-11 21:08

from django.db import migrations, models

import vinyl.lib.dbt_methods


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_alter_asset_resource_alter_asset_workspace_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dbtcoredetails",
            name="version",
            field=models.CharField(
                choices=[
                    (vinyl.lib.dbt_methods.DBTVersion["V1_3"], "1.3"),
                    (vinyl.lib.dbt_methods.DBTVersion["V1_4"], "1.4"),
                    (vinyl.lib.dbt_methods.DBTVersion["V1_5"], "1.5"),
                    (vinyl.lib.dbt_methods.DBTVersion["V1_6"], "1.6"),
                    (vinyl.lib.dbt_methods.DBTVersion["V1_7"], "1.7"),
                    (vinyl.lib.dbt_methods.DBTVersion["V1_8"], "1.8"),
                ],
                max_length=255,
            ),
        ),
    ]
