# Generated by Django 5.0.6 on 2024-09-11 21:04

import app.utils.fields
import django.db.models.deletion
import vinyl.lib.dbt_methods
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_asset_resource_alter_asset_workspace_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedshiftDetails",
            fields=[
                (
                    "dbdetails_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.dbdetails",
                    ),
                ),
                ("subtype", models.CharField(default="redshift", max_length=255)),
                ("host", app.utils.fields.encrypt(models.CharField(max_length=255))),
                ("port", models.IntegerField()),
                (
                    "database",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
                (
                    "username",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
                (
                    "password",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
                ("serverless", models.BooleanField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("app.dbdetails",),
        ),
        migrations.AlterField(
            model_name="dbtcoredetails",
            name="version",
            field=models.CharField(
                choices=[
                    (vinyl.lib.dbt_methods.DBTVersion["V1_3"], "1.3"),
                    (vinyl.lib.dbt_methods.DBTVersion["V1_4"], "1.4"),
                    (vinyl.lib.dbt_methods.DBTVersion["V1_5"], "1.5"),
                    (vinyl.lib.dbt_methods.DBTVersion["V1_6"], "1.6"),
                    (vinyl.lib.dbt_methods.DBTVersion["V1_7"], "1.7"),
                    (vinyl.lib.dbt_methods.DBTVersion["V1_8"], "1.8"),
                ],
                max_length=255,
            ),
        ),
    ]
