# Generated by Django 5.0.6 on 2024-09-12 01:04
from django.db import migrations, models


def convert_uuid_to_autofield(apps, schema_editor):
    Workspace = apps.get_model("app", "Workspace")

    # Create a temporary AutoField
    schema_editor.execute(
        "ALTER TABLE app_workspace ADD COLUMN temp_id SERIAL PRIMARY KEY"
    )

    # Copy data from old UUID field to new AutoField
    for workspace in Workspace.objects.all():
        schema_editor.execute(
            f"UPDATE app_workspace SET temp_id = {workspace.id} WHERE id = '{workspace.id}'"
        )

    # Drop the old UUID field
    schema_editor.execute("ALTER TABLE app_workspace DROP COLUMN id")

    # Rename the new field to 'id'
    schema_editor.execute("ALTER TABLE app_workspace RENAME COLUMN temp_id TO id")


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_dbtcoredetails_version"),
    ]

    operations = [
        migrations.RunPython(convert_uuid_to_autofield),
        migrations.AlterField(
            model_name="workspace",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
