# Generated by Django 5.0.6 on 2024-09-11 21:12

import app.utils.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_dbtcoredetails_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedshiftDetails",
            fields=[
                (
                    "dbdetails_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.dbdetails",
                    ),
                ),
                ("subtype", models.CharField(default="redshift", max_length=255)),
                ("host", app.utils.fields.encrypt(models.CharField(max_length=255))),
                ("port", models.IntegerField()),
                (
                    "database",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
                (
                    "username",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
                (
                    "password",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
                ("serverless", models.BooleanField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("app.dbdetails",),
        ),
    ]
