# Generated by Django 5.0.6 on 2024-07-17 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import app.models
import app.utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_resource_parent_resource"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(choices=[("looker", "Looker")], max_length=255),
                ),
                ("details", app.utils.fields.EncryptedJSONField()),
                (
                    "creator",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="app.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "credentials",
            },
        ),
        migrations.CreateModel(
            name="LookerCredentials",
            fields=[
                (
                    "credentials_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.credentials",
                    ),
                ),
                ("base_url", models.URLField()),
                ("client_id", models.CharField(max_length=255)),
                ("client_secret", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("app.credentials",),
        ),
    ]
