# Generated by Django 5.0.6 on 2024-09-12 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_convert_workspace_id_to_autofield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asseterror",
            name="workspace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.workspace",
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
