# Generated by Django 5.0.6 on 2024-09-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_redshiftdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
