# Generated by Django 5.0.6 on 2024-07-17 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_credentials_lookercredentials"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="credentials",
            table="app_credentials",
        ),
    ]
