# Generated by Django 5.0.6 on 2024-07-17 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_notebook_contents"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notebook",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="notebook",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="notebook",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="notebook",
            name="updated_by",
        ),
        migrations.AddField(
            model_name="notebook",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notebooks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notebook",
            name="workspace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notebooks",
                to="app.workspace",
            ),
        ),
    ]
