# Generated by Django 5.0.6 on 2024-09-16 16:47

import app.models.workspace
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_workspace_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="id",
            field=models.CharField(
                default=app.models.workspace.generate_short_uuid,
                editable=False,
                max_length=6,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
