# Generated by Django 5.0.6 on 2024-09-16 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_workspace_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asseterror",
            name="workspace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.workspace",
            ),
        ),
    ]
