# Generated by Django 5.0.6 on 2024-07-17 03:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_remove_notebook_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notebook",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="notebook",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
