# Generated by Django 5.0.6 on 2024-07-18 03:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_notebook_created_at_notebook_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blocklink",
            name="source",
        ),
        migrations.RemoveField(
            model_name="blocklink",
            name="target",
        ),
        migrations.RemoveField(
            model_name="notebookblock",
            name="block",
        ),
        migrations.RemoveField(
            model_name="notebookblock",
            name="notebook",
        ),
        migrations.RemoveIndex(
            model_name="block",
            name="app_block_tenant__384a0e_idx",
        ),
        migrations.RemoveField(
            model_name="block",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="block",
            name="tenant_id",
        ),
        migrations.RemoveField(
            model_name="block",
            name="updated_by",
        ),
        migrations.AddField(
            model_name="block",
            name="notebook",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocks",
                to="app.notebook",
            ),
        ),
        migrations.AddField(
            model_name="block",
            name="results",
            field=models.FileField(null=True, upload_to="results/"),
        ),
        migrations.AlterField(
            model_name="block",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="block",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name="BlockLink",
        ),
        migrations.DeleteModel(
            name="NotebookBlock",
        ),
    ]
