# Generated by Django 5.0.6 on 2024-09-16 20:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_alter_asseterror_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="assets_exclude_name_contains",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), default=list, size=None
            ),
        ),
    ]
