# Generated by Django 5.0.6 on 2024-09-26 09:13

import app.services.storage_backends
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_workspace_assets_exclude_name_contains"),
    ]

    operations = [
        migrations.CreateModel(
            name="DBTQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("dbt_sql", models.TextField(null=True)),
                (
                    "results",
                    models.FileField(
                        null=True,
                        storage=app.services.storage_backends.CustomS3Boto3Storage(),
                        upload_to="dbt_query_results/",
                    ),
                ),
                (
                    "dbtresource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.dbtresource",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.workspace"
                    ),
                ),
            ],
        ),
    ]
