# Generated by Django 5.0.6 on 2024-07-22 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_credentials_table"),
        ("app", "0015_block_resource"),
    ]

    operations = []
