# Generated by Django 5.0.6 on 2024-10-08 20:07

import app.utils.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_alter_resource_workspace_dbtquery"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dbtcoredetails",
            name="github_installation",
        ),
        migrations.RemoveField(
            model_name="lookerdetails",
            name="github_installation",
        ),
        migrations.RemoveField(
            model_name="dbtcoredetails",
            name="deploy_key",
        ),
        migrations.RemoveField(
            model_name="dbtcoredetails",
            name="git_repo_url",
        ),
        migrations.RemoveField(
            model_name="dbtcoredetails",
            name="github_repo_id",
        ),
        migrations.RemoveField(
            model_name="dbtcoredetails",
            name="main_git_branch",
        ),
        migrations.AlterField(
            model_name="sshkey",
            name="private_key",
            field=app.utils.fields.encrypt(models.TextField()),
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("branch_name", models.CharField(max_length=255)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.workspace"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dbtquery",
            name="branch",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.branch"
            ),
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("main_branch_name", models.CharField(default="main", max_length=255)),
                ("git_repo_url", models.URLField()),
                (
                    "ssh_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.sshkey"
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.workspace"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="branch",
            name="repository",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="app.repository",
            ),
        ),
        migrations.AddField(
            model_name="dbtcoredetails",
            name="repository",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.repository",
            ),
        ),
        migrations.AddField(
            model_name="lookerdetails",
            name="repository",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.repository",
            ),
        ),
        migrations.DeleteModel(
            name="GithubInstallation",
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(
                fields=["workspace_id"], name="app_reposit_workspa_3bc0a3_idx"
            ),
        ),
    ]
