# Generated by Django 5.0.6 on 2024-07-30 16:12

import app.services.storage_backends
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_merge_20240722_0838"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubinstallation",
            name="git_repo_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="githubinstallation",
            name="git_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="githubinstallation",
            name="main_git_branch",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="githubinstallation",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="githubinstallation",
            name="ssh_key",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="icon_file",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=app.services.storage_backends.PublicMediaStorage(),
                upload_to="assets/icons/",
            ),
        ),
        migrations.CreateModel(
            name="SSHKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("public_key", models.TextField()),
                ("private_key", models.TextField()),
                ("tenant_id", models.TextField(null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant_id"], name="app_sshkey_tenant__cb75b8_idx"
                    )
                ],
            },
        ),
    ]
