# Generated by Django 5.0.6 on 2024-10-10 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_remove_dbtcoredetails_github_installation_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="branch",
            unique_together={("branch_name", "repository", "workspace")},
        ),
    ]
