# Generated by Django 5.0.6 on 2024-07-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_resourcedetails_dbtresource_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="resourcedetails",
            new_name="app_resourc_resourc_4c9b2d_idx",
            old_name="app_resourc_resourc_cf97f1_idx",
        ),
        migrations.RemoveField(
            model_name="assetlink",
            name="type",
        ),
        migrations.AlterField(
            model_name="columnlink",
            name="lineage_type",
            field=models.CharField(
                choices=[("all", "All"), ("direct_only", "Direct Only")], max_length=255
            ),
        ),
        migrations.AlterModelTable(
            name="resourcedetails",
            table=None,
        ),
    ]
