# Generated by Django 5.0.6 on 2024-10-23 20:04

import app.services.storage_backends
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_powerbidetails_alter_assetcontainer_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dbtquery",
            name="user_id",
        ),
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("sql", models.TextField(null=True)),
                (
                    "results",
                    models.FileField(
                        null=True,
                        storage=app.services.storage_backends.CustomS3Boto3Storage(),
                        upload_to="query_results/",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.branch",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.resource"
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.workspace"
                    ),
                ),
            ],
        ),
    ]
