# Generated by Django 5.0.6 on 2024-10-17 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_powerbidetails_alter_assetcontainer_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetlink",
            name="source_resource",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_resources",
                to="app.resource",
            ),
        ),
        migrations.AddField(
            model_name="assetlink",
            name="target_resource",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_resources",
                to="app.resource",
            ),
        ),
    ]
