# Generated by Django 5.0.6 on 2024-10-25 17:17

import app.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_powerbidetails_alter_assetcontainer_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="api_key_metabase",
            field=app.utils.fields.encrypt(
                models.CharField(blank=True, max_length=255, null=True)
            ),
        ),
    ]
