# Generated by Django 5.0.6 on 2024-10-27 01:09

import app.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_workspace_api_key_metabase"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="jwt_shared_secret_metabase",
            field=app.utils.fields.encrypt(
                models.CharField(blank=True, max_length=255, null=True)
            ),
        ),
    ]
