# Generated by Django 5.0.6 on 2024-10-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_remove_dbtquery_user_id_query"),
    ]

    operations = [
        migrations.AddField(
            model_name="bigquerydetails",
            name="region",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
