# Generated by Django 5.0.6 on 2024-10-27 18:19

import app.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_workspace_jwt_shared_secret_metabase"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workspace",
            name="api_key_metabase",
        ),
        migrations.RemoveField(
            model_name="workspace",
            name="jwt_shared_secret_metabase",
        ),
        migrations.AddField(
            model_name="metabasedetails",
            name="api_key",
            field=app.utils.fields.encrypt(
                models.CharField(blank=True, max_length=255, null=True)
            ),
        ),
        migrations.AddField(
            model_name="metabasedetails",
            name="jwt_shared_secret",
            field=app.utils.fields.encrypt(
                models.CharField(blank=True, max_length=255, null=True)
            ),
        ),
    ]
