# Generated by Django 5.0.6 on 2024-11-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_metabasedetails_add_api_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="git_repo_url",
            field=models.CharField(max_length=255),
        ),
    ]
