# Generated by Django 5.0.6 on 2024-11-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_alter_repository_git_repo_url"),
        ("app", "0021_scheduledworkflow_remove_ingesterror_workflow_run_and_more"),
    ]

    operations = []
