# Generated by Django 5.0.6 on 2024-08-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_alter_assetlink_id_alter_columnlink_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="lookerdetails",
            name="project_path",
            field=models.CharField(default=".", max_length=255),
            preserve_default=False,
        ),
    ]
