# Generated by Django 5.0.6 on 2024-11-02 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_alter_repository_git_repo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="created_by",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="branch",
            name="name",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="branch",
            name="read_only",
            field=models.BooleanField(default=False),
        ),
    ]
