# Generated by Django 5.0.6 on 2024-11-06 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_scheduledworkflow_remove_ingesterror_workflow_run_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dbtorchestrator",
            name="resource",
        ),
        migrations.AddField(
            model_name="dbtorchestrator",
            name="refresh_artifacts",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="dbtresource",
            name="environment",
            field=models.CharField(
                choices=[
                    ("dev", "Dev"),
                    ("staging", "Staging"),
                    ("prod", "Prod"),
                    ("combined", "Combined"),
                ],
                default="combined",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "branch_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.branch",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "dbtresource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.dbtresource",
                    ),
                ),
            ],
            bases=("app.branch",),
        ),
        migrations.AlterField(
            model_name="dbtorchestrator",
            name="branch",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.project"
            ),
        ),
    ]
