# Generated by Django 5.0.6 on 2024-11-06 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_branch_created_by_branch_name_branch_read_only"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="created_by",
        ),
    ]
