# Generated by Django 5.0.6 on 2024-11-06 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_merge_20241106_1720"),
        ("app", "0023_remove_branch_created_by"),
    ]

    operations = []
