# Generated by Django 5.0.6 on 2024-11-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_branch_schema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="schema",
            field=models.CharField(default="schema", max_length=255),
            preserve_default=False,
        ),
    ]
