# Generated by Django 5.0.6 on 2024-11-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_alter_branch_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbtcoredetails",
            name="target_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
