# Generated by Django 5.0.6 on 2024-11-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_dbtcoredetails_target_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="bigquerydetails",
            name="location",
            field=models.CharField(default="US", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="dbtcoredetails",
            name="threads",
            field=models.IntegerField(default=1),
        ),
    ]
