# Generated by Django 5.0.6 on 2024-11-12 20:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_bigquerydetails_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="query",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="dbtorchestrator",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="dbtquery",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="dbtorchestrator",
            name="resource",
        ),
        migrations.AddField(
            model_name="dbtorchestrator",
            name="refresh_artifacts",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="dbtresource",
            name="environment",
            field=models.CharField(
                choices=[
                    ("dev", "Dev"),
                    ("staging", "Staging"),
                    ("prod", "Prod"),
                    ("combined", "Combined"),
                ],
                default="combined",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("branch_name", models.CharField(max_length=255)),
                ("read_only", models.BooleanField(default=False)),
                ("schema", models.CharField(max_length=255)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="app.repository",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.workspace"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dbtorchestrator",
            name="project",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.project"
            ),
        ),
        migrations.AddField(
            model_name="dbtquery",
            name="project",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.project"
            ),
        ),
        migrations.AddField(
            model_name="query",
            name="project",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.project"
            ),
        ),
        migrations.DeleteModel(
            name="Branch",
        ),
    ]
