# Generated by Django 5.0.6 on 2024-11-13 00:50

import app.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_remove_query_branch_remove_dbtorchestrator_branch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bigquerydetails",
            name="bq_project_id",
            field=app.utils.fields.encrypt(
                models.CharField(default=" ", max_length=255)
            ),
            preserve_default=False,
        ),
    ]
