# Generated by Django 5.0.6 on 2024-11-13 16:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_bigquerydetails_bq_project_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbtcoredetails",
            name="compile_exclusions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), null=True, size=None
            ),
        ),
    ]
