# Generated by Django 5.0.6 on 2024-11-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_dbtcoredetails_compile_exclusions"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="source_branch",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
