# Generated by Django 5.1.3 on 2024-11-20 16:03

import app.models.resources
import app.models.workflows
import app.services.storage_backends
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_dbtcoredetails_compile_exclusions"),
        ("django_celery_results", "0011_taskresult_periodic_task_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dbtorchestrator",
            old_name="dbt_resource",
            new_name="dbtresource",
        ),
        migrations.RenameField(
            model_name="dbtorchestrator",
            old_name="refresh_artifacts",
            new_name="save_artifacts",
        ),
        migrations.RemoveField(
            model_name="dbtresource",
            name="catalog_json",
        ),
        migrations.RemoveField(
            model_name="dbtresource",
            name="manifest_json",
        ),
        migrations.AddField(
            model_name="dbtresource",
            name="artifact_source",
            field=models.CharField(
                choices=[
                    ("metadata", "Metadata Sync"),
                    ("orchestration", "Orchestration"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dbtresource",
            name="catalog",
            field=models.FileField(
                null=True,
                storage=app.services.storage_backends.CustomS3Boto3Storage(),
                upload_to=app.models.resources.custom_dbtresource_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="dbtresource",
            name="manifest",
            field=models.FileField(
                null=True,
                storage=app.services.storage_backends.CustomS3Boto3Storage(),
                upload_to=app.models.resources.custom_dbtresource_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="source_branch",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="datahub_db",
            field=models.FileField(
                null=True,
                storage=app.services.storage_backends.CustomS3Boto3Storage(),
                upload_to="datahub_dbs/",
            ),
        ),
        migrations.CreateModel(
            name="TaskArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "artifact",
                    models.FileField(
                        storage=app.services.storage_backends.CustomS3Boto3Storage(),
                        upload_to=app.models.workflows.custom_upload_to,
                    ),
                ),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("manifest", "manifest.json"),
                            ("catalog", "catalog.json"),
                            ("target", "target.zip"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_celery_results.taskresult",
                        to_field="task_id",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.workspace"
                    ),
                ),
            ],
        ),
    ]
