# Generated by Django 5.1.3 on 2024-11-23 18:49

import app.models.settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_workspacesettings_alter_block_results_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storagesettings",
            name="applies_to",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("data", "Data"), ("metadata", "Metadata")], max_length=255
                ),
                default=app.models.settings.StorageSettings.get_default_categories,
                null=True,
                size=None,
            ),
        ),
    ]
