# Generated by Django 5.1.3 on 2024-12-03 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0037_dbtorchestrator_name"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledworkflow",
            name="clocked",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_celery_beat.clockedschedule",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledworkflow",
            name="crontab",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_celery_beat.crontabschedule",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledworkflow",
            name="periodic_task",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_celery_beat.periodictask",
            ),
        ),
    ]
