# Generated by Django 5.1.3 on 2024-12-04 00:10

import app.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_workspace_anthropic_api_key_workspace_openai_api_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="anthropic_api_key",
            field=app.utils.fields.encrypt(
                models.CharField(blank=True, max_length=255, null=True)
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="openai_api_key",
            field=app.utils.fields.encrypt(
                models.CharField(blank=True, max_length=255, null=True)
            ),
        ),
    ]
