# Generated by Django 5.1.3 on 2024-11-26 21:00

from django.db import migrations, models

import app.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_alter_scheduledworkflow_clocked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="anthropic_api_key",
            field=app.utils.fields.encrypt(
                models.CharField(blank=True, max_length=255, null=True)
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="openai_api_key",
            field=app.utils.fields.encrypt(
                models.CharField(blank=True, max_length=255, null=True)
            ),
        ),
    ]
