# Generated by Django 5.1.3 on 2024-12-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0039_project_created_at_project_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
