# Generated by Django 5.1.3 on 2024-12-06 00:19

import app.models.settings
import app.services.storage_backends
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0040_project_created_at_project_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbtresource",
            name="exported_catalog",
            field=app.services.storage_backends.CustomFileField(
                null=True, storage_category="export", upload_to="."
            ),
        ),
        migrations.AddField(
            model_name="dbtresource",
            name="exported_manifest",
            field=app.services.storage_backends.CustomFileField(
                null=True, storage_category="export", upload_to="."
            ),
        ),
        migrations.AddField(
            model_name="dbtresource",
            name="exported_run_results",
            field=app.services.storage_backends.CustomFileField(
                null=True, storage_category="export", upload_to="."
            ),
        ),
        migrations.AlterField(
            model_name="storagesettings",
            name="applies_to",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("data", "Data"),
                        ("metadata", "Metadata"),
                        ("export", "Export"),
                    ],
                    max_length=255,
                ),
                default=app.models.settings.StorageSettings.get_default_categories,
                null=True,
                size=None,
            ),
        ),
    ]
