# Generated by Django 5.1.3 on 2024-12-05 18:43

import app.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0040_project_created_at_project_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledworkflow",
            name="hmac_secret_key",
            field=app.utils.fields.encrypt(models.CharField(max_length=255, null=True)),
        ),
        migrations.AlterField(
            model_name="scheduledworkflow",
            name="workflow_type",
            field=models.CharField(
                choices=[
                    ("cron", "Cron"),
                    ("one_time", "One Time"),
                    ("webhook", "Webhook"),
                ],
                editable=False,
                max_length=255,
            ),
        ),
    ]
