# Generated by Django 5.1.3 on 2024-12-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0041_dbtresource_exported_catalog_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduledworkflow",
            name="replacement_identifier",
        ),
    ]
