# Generated by Django 5.1.3 on 2024-12-06 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0041_dbtresource_exported_catalog_and_more"),
        ("app", "0041_scheduledworkflow_hmac_secret_key_and_more"),
    ]

    operations = []
