# Generated by Django 5.1.3 on 2024-12-06 20:46

from django.db import migrations, models

import app.models.workflows


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0042_remove_scheduledworkflow_replacement_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledworkflow",
            name="id",
            field=models.CharField(
                default=app.models.workflows.uuid_str,
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
