# Generated by Django 5.1.3 on 2024-12-06 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0043_alter_scheduledworkflow_id"),
        ("django_celery_results", "0013_remove_taskresult_periodic_task_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskartifact",
            name="task",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artifact",
                to="django_celery_results.taskresult",
                to_field="task_id",
            ),
        ),
    ]
