# Generated by Django 5.1.3 on 2024-12-07 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0042_merge_20241206_0421"),
        ("app", "0044_alter_taskartifact_task"),
    ]

    operations = []
