# Generated by Django 5.1.3 on 2024-12-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0045_merge_20241207_0049"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="ai_custom_instructions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
