# Generated by Django 5.1.3 on 2024-12-18 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0047_scheduledworkflow_archived_and_more"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduledworkflow",
            name="archived",
        ),
        migrations.AlterField(
            model_name="scheduledworkflow",
            name="periodic_task",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_celery_beat.periodictask",
            ),
        ),
    ]
