# Generated by Django 5.1.3 on 2024-12-20 21:31

import app.utils.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0048_remove_scheduledworkflow_archived_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClickhouseDetails",
            fields=[
                (
                    "dbdetails_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.dbdetails",
                    ),
                ),
                ("subtype", models.CharField(default="clickhouse", max_length=255)),
                ("host", app.utils.fields.encrypt(models.CharField(max_length=255))),
                ("port", models.IntegerField()),
                ("user", app.utils.fields.encrypt(models.CharField(max_length=255))),
                (
                    "password",
                    app.utils.fields.encrypt(models.CharField(max_length=255)),
                ),
                ("secure", models.BooleanField(null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("app.dbdetails",),
        ),
    ]
