# Generated by Django 5.1.3 on 2024-12-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0048_remove_scheduledworkflow_archived_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbtquery",
            name="force_terminal",
            field=models.BooleanField(default=False),
        ),
    ]
