# Generated by Django 5.1.3 on 2024-12-21 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0049_clickhousedetails"),
        ("app", "0049_dbtquery_force_terminal"),
    ]

    operations = []
